# Generated by Django 6.0.4 on 2026-04-22 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=100)),
                ('speed_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('direction', models.CharField(choices=[('ONE_WAY', 'One Way'), ('TWO_WAY', 'Two Way')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('MAINTENANCE', 'Maintenance')], default='OPEN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('roads', models.ManyToManyField(related_name='intersections', to='roads.road')),
            ],
        ),
    ]
