# Generated by Django 6.0.4 on 2026-04-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_trafficsignal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrafficSignal',
        ),
    ]
