# Generated by Django 6.0.4 on 2026-04-22 19:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BUS', 'Bus'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('EMERGENCY', 'Emergency')], max_length=20)),
                ('speed', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARKED', 'Parked'), ('CHARGING', 'Charging'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('battery_level', models.FloatField(help_text='Battery level percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('current_road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='roads.road')),
            ],
        ),
        migrations.CreateModel(
            name='PriorityVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=255)),
                ('priority_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='Mission progress percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_info', to='vehicles.vehicle')),
            ],
        ),
    ]
