# Generated by Django 6.0.4 on 2026-04-22 20:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roads', '0003_delete_trafficsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RED', 'Red'), ('ORANGE', 'Orange'), ('GREEN', 'Green')], default='RED', max_length=10)),
                ('cycle_duration', models.PositiveIntegerField(help_text='Cycle duration in seconds', validators=[django.core.validators.MinValueValidator(1)])),
                ('mode', models.CharField(choices=[('FIXED', 'Fixed'), ('ADAPTIVE', 'Adaptive')], default='FIXED', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_signals', to='roads.intersection')),
            ],
        ),
    ]
