# Generated by Django 6.0.4 on 2026-04-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('TRAFFIC_JAM', 'Traffic Jam'), ('ROAD_WORK', 'Road Work'), ('HAZARD', 'Hazard'), ('OTHER', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVING', 'Resolving'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='roads.road')),
            ],
        ),
    ]
